Improved deployer? EOM

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -61,6 +61,23 @@ export COLOR_BROWN='\e[0;33m'
 export COLOR_YELLOW='\e[1;33m'
 export COLOR_GRAY='\e[0;30m'
 export COLOR_LIGHT_GRAY='\e[0;37m'
+# export COLOR_NC='[0m' # No Color
+# export COLOR_WHITE='[1;37m'
+# export COLOR_BLACK='[0;30m'
+# export COLOR_BLUE='[0;34m'
+# export COLOR_LIGHT_BLUE='[1;34m'
+# export COLOR_GREEN='[0;32m'
+# export COLOR_LIGHT_GREEN='[1;32m'
+# export COLOR_CYAN='[0;36m'
+# export COLOR_LIGHT_CYAN='[1;36m'
+# export COLOR_RED='[0;31m'
+# export COLOR_LIGHT_RED='[1;31m'
+# export COLOR_PURPLE='[0;35m'
+# export COLOR_LIGHT_PURPLE='[1;35m'
+# export COLOR_BROWN='[0;33m'
+# export COLOR_YELLOW='[1;33m'
+# export COLOR_GRAY='[0;30m'
+# export COLOR_LIGHT_GRAY='[0;37m'
 alias colorslist="set | egrep 'COLOR_\w*'"  # lists all the colors
 
 export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
@@ -89,17 +106,57 @@ alias gk='gitk'
 alias gka='gitk --all'
 
 # Prompts ----------------------------------------------------------
+# These should work! What don't I understand!?
+# SMILEY="${COLOR_GREEN}:)${COLOR_NC}"
+# FROWNY="${COLOR_RED}:(${COLOR_NC}"
+SMILEY=":)"
+FROWNY=":("
+
+function goWell () {
+  if [ $? = 0 ];
+  then
+    echo $SMILEY;
+  else
+    echo $FROWNY;
+  fi
+}
+
+function show_time () {
+  date '+%m-%d %H:%M:%S'
+}
+
+if [[ ! $PROMPT_COMMAND =~ store_exit_status ]]; then
+  export PROMPT_COMMAND="store_exit_status && ${PROMPT_COMMAND:-:}"
+fi
+store_exit_status() {
+  LAST_EXIT_STATUS=$?
+}
+
+# Emits exit status of last command if error condition returned.
+show_exit_status() {
+  if [ "x${LAST_EXIT_STATUS}" != "x0" ]; then
+    echo ${FROWNY}
+  else
+    echo ${SMILEY}
+  fi
+}
+
 # Why won't '\n \[${COLOR_CYAN}\] [ \[${COLOR_YELLOW}\] \W \[${COLOR_CYAN}\] ]$(__git_ps1)\$ \[${COLOR_NC}\]' work?
 type __git_ps1 > /dev/null 2>&1
 if [ 0 -eq $? ]
 then
-export PS1='\n\[\e[0;36m\][\[\e[1;33m\]\W\[\e[0;36m\]]\[\e[1;32m\]$(__git_ps1)\[\e[0;36m\]\$ \[\e[0m\]'
+  #export PS1="\n$(hostname) \[[0;36m\][\[[1;33m\]\W\[[0;36m\]]\[[1;32m\]$(__git_ps1)\[[0;36m\]\$ \[[0m\]"
+  export PS1='\n\! @ $(show_time): $(show_exit_status)\n\[\u@$(hostname)\]:\w $(__git_ps1)\n\$ '
 else
-export PS1='\n\[\e[0;36m\][\[\e[1;33m\]\W\[\e[0;36m\]]\[\e[1;32m\]\[\e[0;36m\]\$ \[\e[0m\]'
+  export PS1="\n$(hostname):\w\n\$ "
 fi
-export PS2='\[\e[1;33m\]>\[\e[0m\] '
-export PS3='\[\e[1;33m\]#?\[\e[0m\] '
-export PS4='\[\e[1;33m\]+\[\e[0m\] '
+export PS2="${COLOR_YELLOW}>${COLOR_NC} "
+export PS3="${COLOR_YELLOW}#?${COLOR_NC} "
+export PS4="${COLOR_YELLOW}+${COLOR_NC} "
+
+# Functions
+
+. ~/.find-functions.sh
 
 # Aliases
 
@@ -135,9 +192,9 @@ alias ...='cd ../..'
 
 # Misc -------------------------------------------------------------
 alias gr='grep -i'  # Case insensitive grep
-alias f='find . -iname'
+# alias f='find . -iname'
 alias df='df -h'
-alias scr='cd ~; screen -h 50000 -s /bin/bash'
+alias ag='ag --pager "less -R"'
 
 # Shows most used commands, cool script I got this from: http://lifehacker.com/software/how-to/turbocharge-your-terminal-274317.php
 alias profileme="history | awk '{print \$2}' | awk 'BEGIN{FS=\"|\"}{print \$1}' | sort | uniq -c | sort -n | tail -n 20 | sort -nr"
